### PR TITLE
Lab 5

### PR DESCRIPTION
**Pull request by diegocasmo**

### CODE REVIEW

**Review by erla2996 — APPROVED** [review]

**Comment by diegocasmo** [comment]
@erla2996 I have created a CNN which should be enough to get an accuracy > than ~75% in the assignment. I have only added the exported network to this commit (which is enough to see how it performs), but will soon add all the code needed to retrain and play with it (some of it is in Python - like the code that setups the files a structure that MatLab likes, etc). Notice there are a few changes in the ``evaluate_classifier.m`` script (the network needs to be loaded and passed to the classifier function). Also, the pre-process done in ``myclassifier.m`` shouldn't be changed, as the network was trained with those exact settings. Let me know what you think

**Comment by erla2996** [comment]
@diegocasmo : I'll take a look at your code on Thursday or Friday, as it's quite late right now and I'm off to sleep.
I worked a bit with regionprops. The performance is currently unstable, and gives results between 48% and 93% for different subsets of the images. It commonly gives around 48% performance, but it gives 93% performance for the entire image set.

**Comment by erla2996** [comment]
When running `evaluate_classifier.m`, I get an error saying that classify requires at least three arguments. I suspect that matlab only sees the classify documented on [https://se.mathworks.com/help/stats/classify.html](https://se.mathworks.com/help/stats/classify.html) and not the classify for deep learning [https://se.mathworks.com/help/deeplearning/ref/classify.html](https://se.mathworks.com/help/deeplearning/ref/classify.html)? Do you know how to fix this?

**Comment by erla2996** [comment]
I had another look at my code, and my tests were wrong. The classification using regionprops is consistently above 90% performance, with a total of 92 erroneous digits for the entire set of test images. I've tested the classifier on different subsets of 300 contiguous images among the test images, as well as on the entire set of 1200 images.

**Comment by diegocasmo** [comment]
@erla2996 

> When running evaluate_classifier.m, I get an error saying that classify requires at least three arguments

I don't get such error, it seems to me we might have different MatLab versions (I have MatLabR2018a)?

When running the ``evaluate_classifier.m`` (the one that uses the trained net) script I get the following:
``` bash
>> evaluate_classifier

Average precision: 
0.965000

Elapsed time is 17.301612 seconds.
```

I haven't taken a detailed look at ``wip_regionprops.m`` yet, but I tried to run it and I got the following error: ``"Undefined function or variable 'imclean'."`` Is there anything else that I have to include in order to run it?

**Comment by erla2996** [comment]
I had forgot to add the file `imclean.m` to git, it's added now.

I am using Matlab R2018b. The documentation at [https://se.mathworks.com/help/deeplearning/ref/classify.html](url) says that the deep learning `classify` is for Matlab R2018b, and that it was introduced in R2016a. I can also not see anything in the patch notes which would indicate that there would be any problem, so I don't think that it's because of my Matlab version.

**Comment by erla2996** [comment]
When trying to load the `trained_net.mat`, I get the warning `"Variable 'trained_net' originally saved as a SeriesNetwork cannot be instantiated as an object and
will be read in as a uint32."`When loaded, the variable `trained_net` is a 1x6 array of integers. Is that correct?

**Comment by diegocasmo** [comment]
@erla2996 

I took a detailed look at your solution, and it seems to be working fine. I have removed all the neural network stuff, since I believe it's best to submit your solution. Do you plan on working on it more?

**Comment by erla2996** [comment]
I don't think that there is much of a point on working on it more. Maybe we could get one percent better or so, but it doesn't feel as though it is possible to get it much better than it is.

I'll be working on making the code more readable and ensuring that it follows the specifications over the next couple of days.

**Comment by diegocasmo** [comment]
@erla2996 

Cool, if that's the case feel free to submit it when you have time to do it, it looks good to me!

**Pull request merged**
